### ISSUE TITLE
python manage.py celery error!

### ISSUE THREAD

**Issue by land-pack** [miguelgrinberg/flack#1]
I have run the `python manage.py runserver` successful! also can visit the web by browser! but when i run the second command on second terminal,I got those error as below show!
`(flackEnv)frank@ak ~/ak/flackEnv/src/flack $ python manage.py celery
Traceback (most recent call last):
  File "manage.py", line 117, in <module>
    manager.run()
  File "/home/frank/ak/flackEnv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/frank/ak/flackEnv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/frank/ak/flackEnv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 81, in run
    ['venv/bin/celery', 'worker', '-A', 'flack.celery'] + argv)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
is there are any step I missed?

**Comment by miguelgrinberg** [comment]
This was my mistake, I had the command that starts celery with a hardcoded path to my virtual environment, which I call `venv`. I bet you have your virtual environment configured differently. I had fixed it now, as long as you have your virtualenv activated the celery command should work just fine.

Note that to keep the code commits in sync with the PyCon class, I had rebased the fix into the proper place. You will need to run the following commands to update your repo:

    git fetch origin
    git reset --hard origin/master

Keep in mind that these commands will remove any local changes you may have made in the repository.

**Comment by land-pack** [comment]
Thank you Sir! 
I had fixed it . But when I run the `python manage.py celery` ,I got a error ,because I use `Rabbitmq` as broker, and you have set the default broker to `redis`, I know I can set some environment to configure it! But your README file did remind it, so maybe you can update your README file!
