### ISSUE TITLE
how to run socket.io with uWSGI

### ISSUE THREAD

**Issue by sungsooha** [miguelgrinberg/flack#14]
First of all, thank for sharing the great example.

I've developed a web server by following flack example and so far everything works well except deploying the socketio server with uWSGI.

With 'python3 manager.py runserver', it works well.

Here is the script I used to launch the server with uWSGI:
uwsgi --http 127.0.0.1:5000 --http-websockets --master --wsgi-file server/wsgi.py --master --gevent 500 --callable app

On the front-end side, it couldn't establish the socket connection.

Are there anything I miss?

Thanks,
Sungsoo Ha

**Comment by miguelgrinberg** [comment]
Did you look at the uWSGI log for clues?

**Comment by sungsooha** [comment]
HI Miguel,

I tried with flack example. Again, it works well when I run flask web with 'python manage.py runserver'.
I modified uWSGI script as before:
uwsgi --http 127.0.0.1:5000 --wsgi-file flack/wsgi.py --gevent 1000 --http-websockets --master --callable app

I could open flack web page but when I tried to log-in it just stuck there and nothing happens.
After waiting for a while, I got error messages at the front-end:
```
Failed to load resource: net::ERR_EMPTY_RESPONSE
GET http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=Mqs7CHu net::ERR_EMPTY_RESPONSE
```
Here is the uWSGI log.
```
*** Starting uWSGI 2.0.18 (64bit) on [Sun Sep 15 14:08:11 2019] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-62-generic #69~16.04.1-Ubuntu SMP Fri Sep 6 02:43:35 UTC 2019
nodename: visws.csi.bnl.gov
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 20
current working directory: /home/sungsooha/Desktop/CODAR/flack
detected binary path: /home/sungsooha/anaconda3/envs/chimbukows/bin/uwsgi
your processes number limit is 256946
your memory page size is 4096 bytes
detected max file descriptor number: 1024
- async cores set to 1000 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39523 (port auto-assigned) fd 3
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x5624b4447a40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 21036928 bytes (20543 KB) for 1000 cores
*** Operational MODE: async ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5624b4447a40 pid: 32168 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 32168)
spawned uWSGI worker 1 (pid: 32171, cores: 1000)
spawned uWSGI http 1 (pid: 32172)
*** running gevent loop engine [addr:0x5624b349ca10] ***
[pid: 32171|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 683 bytes} [Sun Sep 15 14:08:14 2019] GET / => generated 3711 bytes in 41 msecs (HTTP/1.1 200) 2 headers in 81 bytes (3 switches on core 999)
```
it seems uWSGI didn't detect the socket. Any suggestion?

Thanks,
Sungsoo Ha

**Comment by miguelgrinberg** [comment]
Depending on the application you may need to monkey patch the standard library so that it works well with gevent. Have you done that?

**Comment by sungsooha** [comment]
After adding
```
import gevent.monkey
gevent.monkey.patch_all()
```
to flack/wsgi.py file, it seems work. I could log-in.

But, when I tried to submit a meesage it gives the following errors:
```
Traceback (most recent call last):
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/flask_socketio/__init__.py", line 46, in __call__
    start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/socketio/server.py", line 534, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/engineio/server.py", line 366, in handle_request
    environ, start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/engineio/socket.py", line 106, in handle_get_request
    start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/engineio/socket.py", line 146, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/engineio/async_drivers/eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
[pid: 10953|app: 0|req: 8/7] 127.0.0.1 () {48 vars in 954 bytes} [Sun Sep 15 18:23:00 2019] GET /socket.io/?EIO=3&transport=websocket&sid=652c18a5b579449eb5ac32dad3b98625 => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 998)
connect handler error
Traceback (most recent call last):
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/engineio/server.py", line 535, in _trigger_event
    return self.handlers[event](*args)
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/socketio/server.py", line 688, in _handle_eio_connect
    self.manager.initialize()
  File "/home/sungsooha/anaconda3/envs/chimbukows/lib/python3.7/site-packages/socketio/redis_manager.py", line 67, in initialize
    'with ' + self.server.async_mode)
RuntimeError: Redis requires a monkey patched socket library to work with eventlet
```

**Comment by miguelgrinberg** [comment]
Do you want to use eventlet or gevent? If you want to use gevent, then uninstall eventlet. You are not explicitly stating which one you want, and you have both installed.

**Comment by sungsooha** [comment]
After uninstalling the eventlet, everything works well.
Thank for your prompt response.

**Comment by ZayMinKhant** [comment]
@sungsooha Pls can you show me your success uwsgi result.
